sudo: false
language: generic

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "f.zapata@esciencecenter.nl"

install:
  # Install python
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  # Useful for debugging any issues with conda
  - conda info -a

  # Install virtual enviroment 
  - conda install -c rdkit rdkit==2018.03.4.0
  - conda install dask
  - pip install cytoolz

  # Install the package
  - pip install .[test]
  
script:
  # Run the unitary tests excluding the expensive computations
  - pytest -m "not (slow or long)" --cov=insilico tests
  - coverage xml && coverage report -m

after_success:
  - python-codacy-coverage -r coverage.xml

branches:
  only:
   - master
